tap 'businesscritical/tap'
tap 'cloudfoundry/tap'
tap 'git-duet/tap'
tap 'neovim/neovim'

brew 'bosh-cli', args: ['without-bosh2']
brew 'cf-cli'
brew 'dishy'
brew 'fasd'
brew 'fzf'
brew 'git'
brew 'git-duet'
brew 'go@1.7'
brew 'jq'
brew 'lastpass-cli'
brew 'ruby'
brew 'shellcheck'
brew 'terraform'
brew 'the_silver_searcher'
brew 'tig'
brew 'tree'
brew 'neovim'
brew 'watch'
brew 'wget'

cask 'atom'
cask 'flycut'
cask 'google-chrome'
cask 'google-cloud-sdk'
cask 'intellij-idea'
cask 'iterm2'
cask 'screenhero'
cask 'slack'
